### ISSUE TITLE
Team Copy

### ISSUE THREAD

**Issue by PROFI5** [menof36go/ttt2-role-defibrillator#1]
it would be amazing if this role defib would copy their team too cause theres a doppelganger and lover that can have a different team but not different role

**Comment by mexikoedi** [comment]
Could you please link the "Lover" role. 
Afterwards I will look into it.

**Comment by PROFI5** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2072767570&searchtext=ttt2+cupid

> Could you please link the "Lover" role or elaborate what this role is? Afterwards I will look into it.

https://steamcommunity.com/sharedfiles/filedetails/?id=2072767570&searchtext=ttt2+cupid u have to be cupid at the start of the round and it has to be a traitor and a innocent be fallen in love (or neutral killer)
